# solver/simulator.py
# Maps a standard Kociemba 54-char string (U, R, F, D, L, B) or list
# to its new state after a given move.

# U: 0..8, R: 9..17, F: 18..26, D: 27..35, L: 36..44, B: 45..53
# Cycle definitions generated by coordinate rotation.
# A cycle maps new_index = MOVE[old_index] OR old_index = MOVE[new_index].
# Actually, the generated array maps index -> new position's old index?
# If we do `new_state[i] = old_state[MOVE[i]]`, that means MOVE[i] tells us where the piece AT i came from.

# Wait, `perm.append(find_closest(rot_func(c)))`
# This means for position `i` (which is `c`), its new coordinate is `rot_func(c)`, which lands at index `find_closest(...)`.
# So piece at `i` GOES TO `MOVE[i]`.
# If `p_new[MOVE[i]] = p_old[i]`, we need to invert or just build the new state.

MOVE_PERMS = {
    'U': [2, 5, 8, 1, 4, 7, 0, 3, 6, 20, 19, 18, 12, 13, 14, 15, 16, 17, 38, 37, 36, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 47, 46, 45, 39, 40, 41, 42, 43, 44, 11, 10, 9, 48, 49, 50, 51, 52, 53],
    'D': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 53, 52, 51, 18, 19, 20, 21, 22, 23, 17, 16, 15, 29, 32, 35, 28, 31, 34, 27, 30, 33, 36, 37, 38, 39, 40, 41, 26, 25, 24, 45, 46, 47, 48, 49, 50, 44, 43, 42],
    'F': [0, 1, 2, 3, 4, 5, 9, 12, 15, 29, 10, 11, 28, 13, 14, 27, 16, 17, 20, 23, 26, 19, 22, 25, 18, 21, 24, 38, 41, 44, 30, 31, 32, 33, 34, 35, 36, 37, 8, 39, 40, 7, 42, 43, 6, 45, 46, 47, 48, 49, 50, 51, 52, 53],
    'B': [42, 39, 36, 3, 4, 5, 6, 7, 8, 9, 10, 0, 12, 13, 1, 15, 16, 2, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 17, 14, 11, 33, 37, 38, 34, 40, 41, 35, 43, 44, 47, 50, 53, 46, 49, 52, 45, 48, 51],
    'R': [0, 1, 45, 3, 4, 48, 6, 7, 51, 11, 14, 17, 10, 13, 16, 9, 12, 15, 18, 19, 2, 21, 22, 5, 24, 25, 8, 27, 28, 20, 30, 31, 23, 33, 34, 26, 36, 37, 38, 39, 40, 41, 42, 43, 44, 29, 46, 47, 32, 49, 50, 35, 52, 53],
    'L': [18, 1, 2, 21, 4, 5, 24, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 27, 19, 20, 30, 22, 23, 33, 25, 26, 53, 28, 29, 50, 31, 32, 47, 34, 35, 38, 41, 44, 37, 40, 43, 36, 39, 42, 45, 46, 6, 48, 49, 3, 51, 52, 0]
}

def apply_move(state_list, move):
    """
    Applies a move (e.g., 'U', 'U2', "U'") to a 54-element state list.
    Returns a new 54-element state list.
    """
    if len(state_list) != 54:
        raise ValueError("State list must be 54 elements long")
        
    base_move = move[0]
    if base_move not in MOVE_PERMS:
        return list(state_list)
        
    times = 1
    if len(move) > 1:
        if move[1] == '2':
            times = 2
        elif move[1] == "'":
            times = 3
            
    current_state = list(state_list)
    perm = MOVE_PERMS[base_move]
    
    for _ in range(times):
        next_state = [None] * 54
        for i in range(54):
            # The piece at index i goes to index perm[i]
            next_state[perm[i]] = current_state[i]
        current_state = next_state
        
    return current_state

def faces_to_kociemba_list(faces):
    """
    Converts our scanned_faces order (F, L, B, R, U, D) to Kociemba order (U, R, F, D, L, B).
    faces is a list of 6 lists, each of 9 colors.
    """
    # map names to indices in faces list
    # scanned: F=0, L=1, B=2, R=3, U=4, D=5
    # Kociemba order: U, R, F, D, L, B
    indices = [4, 3, 0, 5, 1, 2]
    flat = []
    for idx in indices:
        flat.extend(faces[idx])
    return flat

def kociemba_list_to_faces(kociemba_list):
    """
    Converts 54-element Kociemba list back to scanned_faces order (F, L, B, R, U, D).
    """
    # Kociemba order: U=0, R=1, F=2, D=3, L=4, B=5
    # We want F, L, B, R, U, D
    # F is slice 2, L is slice 4, B is slice 5, R is slice 1, U is slice 0, D is slice 3
    order = [2, 4, 5, 1, 0, 3]
    faces = []
    for idx in order:
        faces.append(kociemba_list[idx*9 : (idx+1)*9])
    return faces
